### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest;

### ISSUE THREAD

**Issue by kunal52** [myinnos/AwesomeImagePicker#11]
java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.techweblearn.onlinechatapp-1/split_lib_dependencies_apk.apk:classes46.dex)
                                                                                    at in.myinnos.awesomeimagepicker.adapter.CustomAlbumSelectAdapter.getView(CustomAlbumSelectAdapter.java:60)
                                                                                    at android.widget.AbsListView.obtainView(AbsListView.java:2346)
                                                                                    at android.widget.GridView.onMeasure(GridView.java:1065)
                                                                                    at android.view.View.measure(View.java:18827)
                                                                                    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                                                                                    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                                                                                    at android.view.View.measure(View.java:18827)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                    at android.view.View.measure(View.java:18827)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                    at android.view.View.measure(View.java:18827)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                    at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                                    at android.view.View.measure(View.java:18827)
                                                                                    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2136)
                                                                                    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1248)
                                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1484)
                                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
                                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6064)
                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                                    at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                                    at android.os.Handler.handleCallback(Handler.java:742)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:157)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5549)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)

**Comment by comm1x** [comment]
Has the same issue. Get it after upgrade from glide v3 to v4.

**Comment by kunal52** [comment]
Yes downgrade to v3 runs correctly

**Comment by comm1x** [comment]
@kunal52 Seriously? May by you suggest to downgrade a whole project to v3?

**Comment by comm1x** [comment]
Why you close this issue? I cant downgrade, we use v4 in our project.

**Comment by kunal52** [comment]
I use other image picker but the problem is still there issue is not with image picker but with glide library

**Comment by devganiyahitesh1** [comment]
+1

**Comment by NikoMontana** [comment]
+1
