### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by amer-alzibak** [myinnos/AwesomeImagePicker#3]
why throw Exception when rotate screen at image picker Activity ! 

FATAL EXCEPTION: main
                                                                                   Process: scit.com.appointmentsmanagmentsys, PID: 25427
                                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{scit.com.appointmentsmanagmentsys/in.myinnos.awesomeimagepicker.activities.AlbumSelectActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.Toolbar$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/toolbar. Make sure other views do not use the same id.
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2461)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2521)
                                                                                       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4164)
                                                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:150)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5517)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                    Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.Toolbar$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/toolbar. Make sure other views do not use the same id.

**Comment by firdausmaulan** [comment]
I've fix this issue, when I add this code in manifest.
<activity android:name="in.myinnos.awesomeimagepicker.activities.AlbumSelectActivity" android:screenOrientation="portrait" />
<activity android:name="in.myinnos.awesomeimagepicker.activities.ImageSelectActivity" android:screenOrientation="portrait" />

**Comment by myinnos** [comment]
Fixed in [v1.02](https://github.com/myinnos/AwesomeImagePicker/releases/tag/1.0.2)
